# Site settings
title: Everpay, the payments start up
email:
description:Everpay makes everday commerce a simple process and is also a provider of payment management solutions.

baseurl: "" # the subpath of your site, e.g. /blog/ (If you use organization leave empty)
url: "https://everpay.github.io" # the base hostname & protocol for your site

#Google Ad Words Data from scripts code (using Google responsive options) and ad client
data-ad-slot: 2973388149
data-ad-client: ca-pub-9204963049240271
google_ad_client: ca-pub-9204963049240271

google_analytics: "UA-2221655-42"
addthis_id: ra-5644da281510c62f
disqus_account: everpay

# Social networks usernames (many more available: flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.) see all icon at fontawesome.io
social:
  - title: twitter
    url: https://twitter.com/everpay
  - title: facebook
    url: https://facebook.com/everpay
  - title: google-plus
    url: https://plus.google.com/+Everpay
  - title: github
    url: http://github.com/everpay
  - title: linkedin
    url: http://linkedin.com/company/everpay
    
# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
# Build settings
